export const ActionTypes={
    SET_ITEMS:"SET_ITEMS",
    SELECTED_ITEM:"SELECTED_ITEM",
    REMOVE_SECLECTED_ITEM:"REMOVE_SECLECTED_ITEM",
    SET_TOTAL_PRICE:"SET_TOTAL_PRICE",
    INCREMENT:"INCREMENT",
    DECREMENT:"DECREMENT",
    REMOVEITEM:"REMOVEITEM",

   
    };